# Generated by Django 4.2.3 on 2023-07-18 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('user_name', models.CharField(max_length=50)),
                ('gender', models.CharField(max_length=100)),
                ('college_mail_id', models.EmailField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('pincode', models.IntegerField(max_length=6)),
                ('college_name', models.CharField(max_length=50)),
                ('degree', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('branch', models.CharField(max_length=20)),
                ('graduated_year', models.IntegerField()),
                ('country', models.CharField(max_length=50, verbose_name='INDIA')),
            ],
        ),
    ]
