# Generated by Django 4.2.3 on 2023-07-19 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_registration_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='branch',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='college_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='country',
            field=models.CharField(default='INDIA', max_length=50),
        ),
    ]
