# Generated by Django 4.2.3 on 2023-07-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_registration_branch_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='collegedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('college_mail_id', models.EmailField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('graduated_year', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='registration',
            name='branch',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='college_mail_id',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='graduated_year',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='region',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='state',
        ),
        migrations.RemoveField(
            model_name='registration',
            name='year',
        ),
    ]
