# Generated by Django 4.2.3 on 2023-07-22 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_delete_collegedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='collegedetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=100)),
                ('college_mail_id', models.EmailField(max_length=100)),
                ('branch', models.CharField(max_length=100)),
                ('degree', models.CharField(max_length=100)),
                ('graduated_year', models.IntegerField()),
                ('state', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
            ],
        ),
    ]
