# Generated by Django 4.2.3 on 2023-07-22 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_collegedetails'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='collegedetails',
            options={'verbose_name_plural': 'College Details'},
        ),
    ]
