# Generated by Django 4.2.3 on 2023-07-22 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_registration_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirm_password',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
